name: Deploy Spring Boot App to Azure

on:
  push:
    branches:
      - main

env:
  ACR_NAME: springbootnodeacr
  APP_NAME: springboot-node-app
  RESOURCE_GROUP: myResourceGroup
  LOCATION: eastus
  IMAGE_TAG: latest

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - run: terraform init
        working-directory: ./terraform
      - run: terraform apply -auto-approve
        working-directory: ./terraform

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Docker Image
        run: |
          docker build -t $ACR_NAME.azurecr.io/$APP_NAME:$IMAGE_TAG .

      - name: Push to Azure Container Registry
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login $ACR_NAME.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin
          docker push $ACR_NAME.azurecr.io/$APP_NAME:$IMAGE_TAG

      - name: Deploy to Azure App Service
        run: |
          az webapp config container set             --name $APP_NAME             --resource-group $RESOURCE_GROUP             --docker-custom-image-name $ACR_NAME.azurecr.io/$APP_NAME:$IMAGE_TAG             --docker-registry-server-url https://$ACR_NAME.azurecr.io             --docker-registry-server-user ${{ secrets.ACR_USERNAME }}             --docker-registry-server-password ${{ secrets.ACR_PASSWORD }}

      - name: Stream Logs from Azure App Service
        run: az webapp log tail --name $APP_NAME --resource-group $RESOURCE_GROUP
